git checkout master
git pull origin master
git merge development
git push origin master

* TODO
** Convert from uniform sampling to uniform random sampling
** Implement Gaussian?
** Implement multiple point selection
** Implement exploration v. exploitation (if EI is all negative, use pure exploration). 
** Updating the NN?
   It seems that updating the NN's dataset is a bad idea. I wonder why...
   It is currently NOT updating the NN's dataset, but retraining based on
   a different architecture...?
   Things that work:
   comment out optimizer.train(), but update NN dataset.
   run optimizer.train(), but do not update NN dataset
** Poor interpolation ONLY in parallel code?
** Trainer is currently broken. Cannot pass feature_extractor in mpi
   Note: commented out feature update in mpi_optimizer. Line 147
   Need to rewrite neural_net.py to make it analogous to linear regression.
   Need to add a params exchange module. 
** Refactor code.
   Stop second guessing myself. 

* Things changed
** optimizer.py
   remove scale
   lim_x updated and renamed as lim_domain
   dataset_X updated
   domain hacked as dataset[:, :-1]
   
** hidden_function.py
   evaluate changed.

** mpi_optimizer.py
   add all() function to contains_row()
   trainer_is_ready set to False
   set plot_it to False
   remove scale
   init_query updated
   domain hacked as dataset[:, :-1]

PUSHED

* Things changed
** optimizer.py
   
** hidden_function.py

** mpi_optimizer.py
   Removed def's 

** mpi_worker.py
   Added

** mpi_trainer.py
   Added

** mpi_worker.py
   Added

PUSHED

* Things changed
** hidden_function.py
   Add comments.
** optimizer.py
   Add comments.
** mpi_trainer.py
   Commented out a bunch of stuff
** mpi_master.py
   Add comments.

* Things changed
** hidden_function.py
   Change hidden function 
** mpi_master.py
   Proper griding
